import {
  ProgressStep,
  CustomerInfo,
  CaseInfo,
  Message,
  Schedule,
  Task,
  Document,
  TimelineItem,
  TaskTemplate,
} from './types';

// 初期表示用（API取得前）。新規案件は事前確認が進行中
export const progressSteps: ProgressStep[] = [
  {
    id: 1,
    title: '事前確認',
    subtitle: '条件チェック',
    status: 'in-progress',
    statusText: '進行中',
  },
  {
    id: 2,
    title: '事前書類収集',
    subtitle: '申請書初案作成',
    status: 'pending',
    statusText: '進行前',
  },
  {
    id: 3,
    title: '申請手続き',
    subtitle: '電子申請完了',
    status: 'pending',
    statusText: '進行前',
  },
  {
    id: 4,
    title: '交付決定',
    subtitle: '通知確認',
    status: 'pending',
    statusText: '進行前',
  },
  {
    id: 5,
    title: '実績報告',
    subtitle: '支出証明提出',
    status: 'pending',
    statusText: '進行前',
  },
  {
    id: 6,
    title: '補助金請求',
    subtitle: '入金確認',
    status: 'pending',
    statusText: '進行前',
  },
];

export const customerInfo: CustomerInfo = {
  name: '田中太郎',
  email: 'tanaka@tech-innovation.co.jp',
  company: '株式会社ABC',
  contact: '03-1234-5678',
  industry: 'IT・テクノロジー',
  region: '東京都',
};

export const caseInfo: CaseInfo = {
  applicationDate: '2024/12/01',
  deadline: '2025/01/15',
  status: '書類準備中',
  assignee: '斎 行政書士',
  assistant: 'ドウ アシスタント',
};

export const messages: Message[] = [
  {
    id: 1,
    sender: '株式会社グリーンテック',
    senderInitial: '山',
    content:
      'お世話になります。株式会社グリーンテックの田中です。\n\n「中小企業デジタル化支援補助金」の申請について、いくつかご質問がございます。\n\nまず、ITツール導入を検討していますが、どのような書類が必要でしょうか。\n\nよろしくお願いいたします。',
    time: '2025年3月31日 午前 09:45',
    isExpert: false,
  },
  {
    id: 2,
    sender: '行政書士',
    senderInitial: '斎',
    content:
      '株式会社グリーンテック　山本様\n\nご連絡いただきありがとうございます。\n行政書士の斎藤です。\n「中小企業デジタル化支援補助金」の申請についてお問い合わせいただき、ありがとうございました。\n\n当該する制度の相談や申請の可否について\nヒアリングを通じて整理していけばと思います。\n\n一旦下記のお問合せ内容をご共有いただければと存じます。\n\n現在導入を検討しているITツールの概要\n会社概要（設立年・従業員数など）',
    time: '2025年1月23日 午後 03:25',
    isExpert: true,
  },
];

export const schedules: Schedule[] = [
  {
    id: 1,
    date: '01/15',
    title: '申請締切',
    statusText: '3日後',
    statusColor: '#FB2C36',
  },
  {
    id: 2,
    date: '01/18',
    title: '書類確認ミーティング',
    statusText: '6日後',
    statusColor: '#9810FA',
  },
];

export const tasks: Task[] = [
  {
    id: 1,
    title: '事業計画書の作成',
    priority: 'high',
    description: '補助金申請に必要な事業計画書を作成してください。',
    assignee: '田中太郎',
    dueDate: '01/10',
    daysLeft: 3,
    status: 'pending',
  },
  {
    id: 2,
    title: '見積書の収集',
    priority: 'high',
    description: 'ITツール導入に関する見積書を3社以上から取得してください。',
    assignee: '田中太郎',
    dueDate: '01/12',
    daysLeft: 5,
    status: 'pending',
  },
  {
    id: 3,
    title: '決算書の準備',
    priority: 'medium',
    description: '直近2期分の決算書をPDF形式で準備してください。',
    assignee: 'ドウ アシスタント',
    dueDate: '01/08',
    daysLeft: 1,
    status: 'in-progress',
  },
  {
    id: 4,
    title: '会社概要書の更新',
    priority: 'low',
    description: '最新の会社情報を反映した会社概要書を作成してください。',
    assignee: '斎 行政書士',
    dueDate: '01/05',
    daysLeft: 0,
    status: 'completed',
  },
];

export const documents: Document[] = [
  {
    id: 1,
    title: '履歴事項全部証明書',
    status: 'approved',
    statusText: '承認',
    date: '2024-12-14 10:00:00',
  },
  {
    id: 2,
    title: '事業計画書',
    status: 'rejected',
    statusText: '却下',
    date: '2024-12-15 14:00:00',
    feedback:
      'フィードバック: 収支計画の詳細が不足しています。3年分の収支見込みを追加してください。',
  },
  {
    id: 3,
    title: '決算書（直近2期分）',
    status: 'reviewing',
    statusText: '検討中',
    date: '2024-12-16 09:00:00',
  },
  {
    id: 4,
    title: '見積書（3社分）',
    status: 'pending',
    statusText: 'アップロード待ち',
    date: '',
  },
];

export const timelineItems: TimelineItem[] = [
  {
    id: 1,
    date: '12月14日',
    time: '午後 02:30',
    dateTime: '2024/12/14 14:30',
    author: '斎 行政書士',
    authorInitial: '斎',
    role: '行政書士',
    roleColor: { bg: '#F3E8FF', text: '#8200DB' },
    actionType: '事業計画書却下',
    actionTypeColor: { bg: '#FFE2E2', border: '#FFC9C9', text: '#C10007' },
    description: '3ページ財務計画部分補完必要',
    targetType: '書類',
    targetValue: '事業計画書',
    avatarBg: '#9810FA',
  },
  {
    id: 2,
    date: '12月14日',
    time: '午前 10:15',
    dateTime: '2024/12/14 10:15',
    author: 'ドウ アシスタント',
    authorInitial: 'キ',
    role: 'アシスタント',
    roleColor: { bg: '#DBEAFE', text: '#1447E6' },
    actionType: '書類検討完了',
    actionTypeColor: { bg: '#DCFCE7', border: '#B9F8CF', text: '#008236' },
    description: '事業者登録証検討完了、異常なし',
    targetType: '書類',
    targetValue: '事業者登録証',
    avatarBg: '#155DFC',
  },
  {
    id: 3,
    date: '12月13日',
    time: '午後 04:45',
    dateTime: '2024/12/13 16:45',
    author: '斎 行政書士',
    authorInitial: '斎',
    role: '行政書士',
    roleColor: { bg: '#F3E8FF', text: '#8200DB' },
    actionType: 'メッセージ送信',
    actionTypeColor: { bg: '#CEFAFE', border: '#A2F4FD', text: '#007595' },
    description: '追加書類要求案内メッセージ送信',
    targetType: '顧客',
    targetValue: 'キム・チョルス',
    avatarBg: '#9810FA',
  },
  {
    id: 4,
    date: '12月13日',
    time: '午後 03:20',
    dateTime: '2024/12/13 15:20',
    author: 'システム',
    authorInitial: 'シ',
    role: 'システム',
    roleColor: { bg: '#F3F4F6', text: '#364153' },
    actionType: '書類アップロード',
    actionTypeColor: { bg: '#F3E8FF', border: '#E9D4FF', text: '#8200DB' },
    description: '顧客が財務報告書をアップロードしました',
    targetType: '書類',
    targetValue: '財務報告書',
    avatarBg: '#4A5565',
  },
  {
    id: 5,
    date: '12月13日',
    time: '午前 09:20',
    dateTime: '2024/12/13 09:20',
    author: 'ドウ アシスタント',
    authorInitial: 'キ',
    role: 'アシスタント',
    roleColor: { bg: '#DBEAFE', text: '#1447E6' },
    actionType: '案件状態変更',
    actionTypeColor: { bg: '#FFEDD4', border: '#FFD6A7', text: '#CA3500' },
    description: '相談中 → 書類準備段階に変更',
    targetType: '案件状態',
    targetValue: '',
    avatarBg: '#155DFC',
  },
  {
    id: 6,
    date: '12月12日',
    time: '午後 03:30',
    dateTime: '2024/12/12 15:30',
    author: '斎 行政書士',
    authorInitial: '斎',
    role: '行政書士',
    roleColor: { bg: '#F3E8FF', text: '#8200DB' },
    actionType: '書類承認',
    actionTypeColor: { bg: '#DCFCE7', border: '#B9F8CF', text: '#008236' },
    description: '事業者登録証承認完了',
    targetType: '書類',
    targetValue: '事業者登録証',
    avatarBg: '#9810FA',
  },
  {
    id: 7,
    date: '12月10日',
    time: '午前 11:00',
    dateTime: '2024/12/10 11:00',
    author: 'システム',
    authorInitial: 'シ',
    role: 'システム',
    roleColor: { bg: '#F3F4F6', text: '#364153' },
    actionType: '書類アップロード',
    actionTypeColor: { bg: '#F3E8FF', border: '#E9D4FF', text: '#8200DB' },
    description: '顧客が事業者登録証をアップロードしました',
    targetType: '書類',
    targetValue: '事業者登録証',
    avatarBg: '#4A5565',
  },
  {
    id: 8,
    date: '12月5日',
    time: '午後 02:20',
    dateTime: '2024/12/05 14:20',
    author: '斎 行政書士',
    authorInitial: '斎',
    role: '行政書士',
    roleColor: { bg: '#F3E8FF', text: '#8200DB' },
    actionType: '担当者指定',
    actionTypeColor: { bg: '#DBEAFE', border: '#BEDBFF', text: '#1447E6' },
    description: 'ドウアシスタントを補助担当者に指定',
    targetType: '案件設定',
    targetValue: '',
    avatarBg: '#9810FA',
  },
  {
    id: 9,
    date: '12月1日',
    time: '午前 10:00',
    dateTime: '2024/12/01 10:00',
    author: '斎 行政書士',
    authorInitial: '斎',
    role: '行政書士',
    roleColor: { bg: '#F3E8FF', text: '#8200DB' },
    actionType: '案件生成',
    actionTypeColor: { bg: '#DCFCE7', border: '#B9F8CF', text: '#008236' },
    description: '若者金案件生成',
    targetType: '案件',
    targetValue: '',
    avatarBg: '#9810FA',
  },
];

export const taskTemplates: TaskTemplate[] = [
  {
    id: 1,
    title: '初回ヒアリング実施',
    description: '顧客から事業内容と補助金活用計画について詳細ヒアリングを実施',
    priority: '高',
    priorityColor: { bg: '#FFE2E2', text: '#C10007' },
    assignee: '行政書士',
    category: 'hearing',
  },
  {
    id: 2,
    title: '事業計画書初案作成',
    description: 'ヒアリング内容を基に事業計画書の初案を作成',
    priority: '高',
    priorityColor: { bg: '#FFE2E2', text: '#C10007' },
    assignee: '行政書士',
    category: 'document',
  },
  {
    id: 3,
    title: '必要書類の収集依頼',
    description: '履歴事項全部証明書、決算書、見積書等の必要書類を顧客に依頼',
    priority: '高',
    priorityColor: { bg: '#FFE2E2', text: '#C10007' },
    assignee: 'アシスタント',
    category: 'document',
  },
  {
    id: 4,
    title: '財務資料の収集と分析',
    description: '直近2期分の決算書、試算表等を収集し、財務分析を実施',
    priority: '高',
    priorityColor: { bg: '#FFE2E2', text: '#C10007' },
    assignee: 'アシスタント',
    category: 'document',
  },
  {
    id: 5,
    title: '認定支援機関との打ち合わせ',
    description: '認定支援機関と事業計画について打ち合わせを実施',
    priority: '高',
    priorityColor: { bg: '#FFE2E2', text: '#C10007' },
    assignee: '行政書士',
    category: 'meeting',
  },
  {
    id: 6,
    title: '事業計画書の顧客確認',
    description: '作成した事業計画書を顧客に確認してもらい、修正箇所を確定',
    priority: '中',
    priorityColor: { bg: '#FEF9C2', text: '#A65F00' },
    assignee: 'アシスタント',
    category: 'review',
  },
];
