import { BuildingIcon, VectorIcon, CalendarIcon } from '@/components/icons';
import { SummaryCard, Subsidy } from './types';

export const summaryCards: SummaryCard[] = [
  {
    id: 1,
    title: '登録済み補助金',
    value: '3',
    icon: BuildingIcon,
    gradient: 'from-[#EFF6FF] to-[#DBEAFE]',
    iconBg: '#3681F7',
    iconColor: '#FFFFFF',
  },
  {
    id: 2,
    title: '進行中の案件',
    value: '24',
    icon: VectorIcon,
    gradient: 'from-[#F0FDF4] to-[#DCFCE7]',
    iconBg: '#00C950',
    iconColor: '#FFFFFF',
  },
  {
    id: 3,
    title: '募集中の補助金',
    value: '0',
    icon: CalendarIcon,
    gradient: 'from-[#FAF5FF] to-[#F3E8FF]',
    iconBg: '#AD46FF',
    iconColor: '#FFFFFF',
  },
];

export const subsidies: Subsidy[] = [
  {
    id: 1,
    status: '公募中',
    statusColor: '#1447E6',
    statusBg: '#DBEAFE',
    statusBorder: '#BBD8FF',
    caseCount: '10件の案件',
    caseCountColor: '#8200DB',
    caseCountBg: '#F3E8FF',
    caseCountBorder: '#E9D4FF',
    title: '令和7年度カスタマーハラスメント防止対策推進事業_企業向け奨励金第3回募集',
    amount: '40万円',
    subsidyRate: '2/3',
    region: '東京都',
    industry: '東京都',
    deadline: '2025年12月24日',
    deadlineUrgent: true,
    description:
      '（公財）東京しごと財団（以下「財団」という。）は、「東京都カスタマー・ハラスメント防止条例（以下「条例」という。）」で規定する事業者による措置等を速やかに企業等へ浸透させるため、カスタマーハラスメント対策に関するマニュアルの作成に加え、カスタマーハラスメントを防止するための実践的な取組を促進し、働きやすい職場環境整備を推進します。',
    tags: ['販売拡大', 'まちづくり'],
    caseNumber: '10件',
  },
  {
    id: 2,
    status: '募集終了',
    statusColor: '#364153',
    statusBg: '#F3F4F6',
    statusBorder: '#E5E7EB',
    caseCount: '3件の案件',
    caseCountColor: '#8200DB',
    caseCountBg: '#F3E8FF',
    caseCountBorder: '#E9D4FF',
    title: '東京都足立区：「熱中症対策応援金」',
    amount: '400万円',
    subsidyRate: '2/3',
    region: '東京都',
    industry: '東京都、全業種',
    deadline: '2025年9月30日',
    deadlineUrgent: true,
    description:
      '物価高騰が続く中、冷房機器等の稼働その他の熱中症対策のために必要な費用に充てるため、東京都から水道の供給を受けておらず、東京都が実施する....',
    tags: ['販売拡大', 'まちづくり'],
    caseNumber: '3件',
  },
  {
    id: 3,
    status: '募集終了',
    statusColor: '#364153',
    statusBg: '#F3F4F6',
    statusBorder: '#E5E7EB',
    caseCount: '3件の案件',
    caseCountColor: '#8200DB',
    caseCountBg: '#F3E8FF',
    caseCountBorder: '#E9D4FF',
    title: '長崎県佐世保市：「佐世保市チャレンジショップ支援事業補助金」',
    amount: '400万円',
    subsidyRate: '100%',
    region: '長崎県',
    industry: '長崎県・小売業・サービス業',
    deadline: '2025年9月30日',
    deadlineUrgent: true,
    description:
      '市内空き店舗の活用及び、新しいビジネスに挑戦する創業者の育成支援を図り、商店街活性化の促進につなげる「チャレンジショップ」を支援します。',
    tags: ['新規創業', '販売拡大'],
    caseNumber: '3件',
  },
];
